### ISSUE TITLE
No Usable Pokestops found in Your Area - Is your maximum distance too small ??

### ISSUE THREAD

**Issue by jawad90** [PocketMobsters/PokeMobBot#327] opened 2016-08-02 02:43 UTC
im farming in an area that has so much pokestops and i got that error that keeps looping over and over did the bot gone too far from the default location ? or its just a bug because if maximum distance too small like it said there are enough pokestops to farm over and over

**Comment by Corlobin** [comment] 2016-08-02 02:48
Here isnt showing any pokestops.

**Comment by DarkShogun34** [comment] 2016-08-02 02:50
I have been having this problem since this morning with the 1.0 release. Someone said to let it run and it run and it would work itself out but it didn't. It got to a point where it told me to hit any key to try again and it restarted tell me no stops available. I tried 3 different very populated areas on different continents.

**Comment by Roxazlp** [comment] 2016-08-02 03:21
Try a different location. Maybe the location is high loaded or unavailable currently.

**Comment by DarkShogun34** [comment] 2016-08-02 03:28
I have tried Disneyland Tokyo, which is the one I was originally using last name and it worked perfectly but I woke up to an error and had to restart the bot. After restarting I got this error about there being no pokestops. I have also tried Sydney Australia, Various places in China, and Disney World in Florida.

**Comment by jawad90** [comment] 2016-08-02 03:35
i just closed and opened it again it was a new update maybe thats why ..seems working fine for now

**Comment by DarkShogun34** [comment] 2016-08-02 03:48
I just upgraded to the newest one and still get the error.

**Comment by rubseneter** [comment] 2016-08-02 12:46
Same problem here since about 30 minutes :(

**Comment by jawad90** [comment] 2016-08-02 16:32
its happening again is there a new update coming ? if yes thats why.. else it has something to do with the maximum distance

**Comment by SirJhary** [comment] 2016-08-02 18:00
I thougth first its just me. Same Problem if i use any other Coords then the default.

**Comment by Theamazinggenko** [comment] 2016-08-03 21:33
i have the same problem

**Comment by GreenGoblinz** [comment] 2016-08-03 22:13
Issue persists, is anyone working on this?

**Comment by Theamazinggenko** [comment] 2016-08-03 22:17
i do not know

**Comment by saamert** [comment] 2016-08-03 22:21
i got the same problem since 1 hour ago.. getting exact the same error over and over again

**Comment by Theamazinggenko** [comment] 2016-08-03 22:22
same

**Comment by pandorasky21** [comment] 2016-08-03 22:30
Samewith me. This "no pokestop nearby" error is looping since i update to 0.6.4,  The thing is when i open my apps and play normally, i can visit pokestop and loot thing. i let my necrobot open like 30 min but still the error persist. is it the apps  have prob or im getting banned?

**Comment by DVN-Anakin** [comment] 2016-08-03 22:48
Just realised there no such file as LastPos.ini in the config folder. Someone really messed it up, seems like I must DIY again :dart: BTW I´m level 23 already (40 is max) so better hope that Niantic is busy right now :D

**Comment by ColorfulShadow** [comment] 2016-08-03 22:48
I have the same problem. It was working fine for me yesterday but today all the bot has been saying is that there isn't any usable poke stops. I've tried changing my location multiple times and I still get the error.

**Comment by Theamazinggenko** [comment] 2016-08-03 22:49
is there a fix dvn anakin

**Comment by DVN-Anakin** [comment] 2016-08-03 22:53
Where exactly? Someone posted a question on this issue (https://github.com/NECROBOTIO/NecroBot/issues/) but it was deleted

**Comment by GreenGoblinz** [comment] 2016-08-03 22:54
It was https://github.com/NECROBOTIO/NecroBot/issues/655 but someone deleted it.

**Comment by ColorfulShadow** [comment] 2016-08-03 22:54
I saw that too :(

**Comment by neojhz** [comment] 2016-08-03 22:54
It seems to be a niantic's api might have changed? I've tried version 0.5.0 of necrobot - no pokestops and this was the stable version I know of...

**Comment by DVN-Anakin** [comment] 2016-08-03 22:57
Yeah probably it has something to do with this recent Pkm GO update http://www.telegraph.co.uk/technology/2016/08/01/pokemon-go-update-angers-players-by-removing-key-features---here/

**Comment by GreenGoblinz** [comment] 2016-08-03 23:00
I take it this wont be resolved today then?

**Comment by DVN-Anakin** [comment] 2016-08-03 23:05
Definitely not I think. It was a matter of time until Niantic figures out how to deal with hackers. Still why did Necrobot launch that  0.6.4 update when they already knew that new Pokemon GO update is coming? That seems very stupid to me.

**Comment by TumsArentCandy** [comment] 2016-08-03 23:10
That really fucking sucks, i am currently a level 34, and have been using necrobot alot, and im going for level 40, and i cannot do this as of now :(

**Comment by neojhz** [comment] 2016-08-03 23:13
Yep. I've tried debugging to old versions of rocket api on GetMapObjects. The method returns no pokestops. Yet, the mobile app is working fine! Could it be the end? :smiling_imp:

**Comment by Nerjo** [comment] 2016-08-03 23:14
Maybe they are banning people? im new to here and i just got this issue

**Comment by arutemauepon** [comment] 2016-08-03 23:17
I tried to check my account by logging into the game and I was able to see nearby pokestops and gym around me so I can confirm that I'm not being banned

**Comment by GreenGoblinz** [comment] 2016-08-03 23:20
I figured, well back to the old method. Btw does anyone know how to get the app to stop transfering rare pokemon? Like the previous version transferred my Kabutos Omaster and Dratinis.. I was so pissed when I logged in and saw them gone! even my Pikachu went adios which was my starter..

**Comment by Nerjo** [comment] 2016-08-03 23:34
when did you guys start getting the issue

**Comment by ColorfulShadow** [comment] 2016-08-03 23:36
I just got it today

**Comment by Nerjo** [comment] 2016-08-03 23:37
same mine was working till like maybe like 3 hours ago

**Comment by ColorfulShadow** [comment] 2016-08-03 23:37
Yep me too

**Comment by saamert** [comment] 2016-08-03 23:41
Same here 3-4 hours ago

**Comment by asalazar-pley** [comment] 2016-08-03 23:43
I just learned about this, got all set up, and got this error, hehehe, I had poor timing.
Looking forward to the great ideas the Development team will come up with to work around this issue.
Kudos to the Devs.

**Comment by Nerjo** [comment] 2016-08-03 23:43
ok guys its not just this bot 
most of the other bots are also down

**Comment by reacherwick** [comment] 2016-08-03 23:44
same issue here

**Comment by ViezeOudeMan** [comment] 2016-08-03 23:44
I also got this , I tried other bots but more of them are down :(

**Comment by ViezeOudeMan** [comment] 2016-08-03 23:44
does anyone kno a fix ?

**Comment by DarkShogun34** [comment] 2016-08-03 23:44
2 days down for me.

**Comment by ViezeOudeMan** [comment] 2016-08-03 23:44
4hours down for me

**Comment by Nerjo** [comment] 2016-08-03 23:46
just wait it out im sure the devs are on it

**Comment by Edaught** [comment] 2016-08-03 23:46
If you could stop complaining and try to understand the situation it would be great. A lot of people are creating needless issues on this github to complain about the bug

**Comment by GreenGoblinz** [comment] 2016-08-03 23:47
Yea.. complaining won't help. I made a macro to keep checking the release page and notify me when there's an update.

**Comment by TumsArentCandy** [comment] 2016-08-03 23:52
They removed last location files so, there wont be a working bot for a while ;(

**Comment by alphazygma** [comment] 2016-08-03 23:53
I just learned about this awesome development, got all set up, and got this error, hehehe, I had poor timing.
Looking forward to the great ideas the Development team will come up with to work around this issue.
Kudos to the Devs.

**Comment by saamert** [comment] 2016-08-03 23:53
Do you have a link of the main page?

**Comment by alphazygma** [comment] 2016-08-03 23:55
Are you looking for this? https://github.com/NECROBOTIO/NecroBot/

**Comment by DVN-Anakin** [comment] 2016-08-03 23:55
Niantic SEO wrote this: "– We have limited access by third-party services which were interfering with our ability to maintain quality of service for our users and to bring Pokémon GO to users around the world. The large number of users has made the roll-out of Pokémon GO around the world an… interesting… challenge. "  

→ Pokémon Go doesn’t have an API so it seems like that NecroBot created countless of accounts on many servers around the world using Android emulators. With these emulators, it could fake movements around cities and reverse-engineer the game to create a sort of lightweight API and gather Pokémon data. Now Niantic puts it to the end.

**Comment by saamert** [comment] 2016-08-03 23:56
So this means its the end of bot using?

**Comment by ColorfulShadow** [comment] 2016-08-03 23:57
Wait did Niantic say the second paragraph or did u write that?

**Comment by Nerjo** [comment] 2016-08-03 23:57
https://twitter.com/MonzterSlayer/status/760986104858161152

**Comment by DVN-Anakin** [comment] 2016-08-03 23:58
Second paragraph is mine :D . It means we can only wait for NecroBot development team

**Comment by bobbytria69** [comment] 2016-08-03 23:58
same, mee too, all of my bots cant detect pokestops .. 4 hours ago

**Comment by ColorfulShadow** [comment] 2016-08-04 00:00
This sucks. I'm just happy I found a good bot that's free. Kinda feel bad for people that paid for bots. I hope the devs can find a way around it.

**Comment by KobiCohen1** [comment] 2016-08-04 00:00
i just found this methood today :( 
hope theyl fix it.

**Comment by bobbytria69** [comment] 2016-08-04 00:11
so how now? just waiting guys? :(

**Comment by alphazygma** [comment] 2016-08-04 00:29
Either that, or what about actually go and play?

**Comment by GreenGoblinz** [comment] 2016-08-04 00:30
Just use gps spoof until they get this working again.

**Comment by Avitar** [comment] 2016-08-04 00:48
My life feels so empty without a bot to farm the 1,000,000 XP I need to level up. Now i have no idea what my pokemon IV's are...

**Comment by OkkieDokkie** [comment] 2016-08-04 01:09
just woke up and look at this shit..
pokestop no usable..

Waiting for new version api again?

**Comment by bearxxwz** [comment] 2016-08-04 01:14
Haha just tried to use this bot to finally catch a growlithe/evolve to arcanine to honor my dog that passed away this month and the bots down. GL n-bot developers I'm cheering for you. Niant has done an awful job at making this game's pokemon remotely accessible. It gets really silly seeing so many pidgey, rats etc, especially when you need AT LEAST 12 or so of the same pokemon to hit 50 candy/evolve.

**Comment by Asriandy** [comment] 2016-08-04 03:52
Yes me too after update to 0.6.4 yesterday

**Comment by Mad-Mom** [comment] 2016-08-04 04:05
Same problem here, cannot detect pokestops.

**Comment by Theamazinggenko** [comment] 2016-08-04 04:10
i just got it and this problem came up

**Comment by arutemauepon** [comment] 2016-08-04 05:12
it wasn't because of the 0.6.4 update.

**Comment by Asriandy** [comment] 2016-08-04 05:20
Yes I have to understand the problem after reading some of the comments above ...
Waiting for update...
Keep the spirit dev ^.^

**Comment by bobbytria69** [comment] 2016-08-04 05:44
spiriittt :* :D

**Comment by kuntoharr** [comment] 2016-08-04 06:13
Why don't we just walk and catch, while waiting for the solution lol.. it's kinda good exercise tho :D

**Comment by TalkativeTom** [comment] 2016-08-04 07:03
yeah... I just found out about the bots and now I'm pissed I updated... shit.

**Comment by mikegrimmers** [comment] 2016-08-04 08:21
On the bright side, it looks like 0.6.4 has a much better transfer config, upon running the bot, before it searched for Pokestops it ran a transfer routine and actually this time took preference with IV (as I set it) and kept the 2 duplicates I set.

**Comment by ghien** [comment] 2016-08-04 08:56
can someone slove the problems yet? ill better donate necrobot rather than buying coins on pokemon go

**Comment by WeTorUs** [comment] 2016-08-04 09:02
hello to everybody, i have the same problem and i think this is the end :(

**Comment by bobbywatsup212** [comment] 2016-08-04 09:05
im having the same issue i have tried a couple of different log ins as well as different locations for each one including Santa Monica pier central park Sydney Australia etc etc ,
there is definatley an issue that cam with the update i hope it gets fixed soon maybe they need to re update a fixed version

**Comment by aryan348** [comment] 2016-08-04 09:06
same problem ......any solution??

**Comment by bobbywatsup212** [comment] 2016-08-04 09:18
None yet mate

**Comment by bobbywatsup212** [comment] 2016-08-04 09:19
Well not that i know of anyway

**Comment by jiminchanga** [comment] 2016-08-04 10:56
aww man :( was depending on this

**Comment by rodmcgee89** [comment] 2016-08-04 11:00
Is it possible to find an older version of the Pokemon GO .apk to install on our devices that is not patched with the latest encrypted API so that we can run our bots like normal?

**Comment by p0c007** [comment] 2016-08-04 11:01
it is the server communication that has changed, so the old apk wont work anymore.

**Comment by rodmcgee89** [comment] 2016-08-04 11:03
Ok I was starting to think it was a server issue

**Comment by mikegrimmers** [comment] 2016-08-04 11:05
Hopefully this isn't the end.




On Thu, Aug 4, 2016 at 12:03 PM +0100, "rodmcgee89" <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok I was starting to think it was a server issue

-

**Comment by OkkieDokkie** [comment] 2016-08-04 13:12
how high level you got ? all of you ..
im almost 40

**Comment by jiminchanga** [comment] 2016-08-04 13:14
level 27 whoopie

**Comment by reacherwick** [comment] 2016-08-04 13:15
Wow 40 nice

**Comment by Theamazinggenko** [comment] 2016-08-04 13:24
plz fix

**Comment by eeelmaito** [comment] 2016-08-04 14:17
Ok its now working for me. It was actually quite an easy fix to the code. I only changed a few lines of the code and its all back to normal now.

**Comment by jiminchanga** [comment] 2016-08-04 14:18
care to share? :))^

**Comment by mikegrimmers** [comment] 2016-08-04 14:18
Please share the fix?

**Comment by reacherwick** [comment] 2016-08-04 14:18
Yea share to us

**Comment by JSleemanII** [comment] 2016-08-04 14:29
I am guessing he is just trolling us

**Comment by dawe123** [comment] 2016-08-04 14:29
Well, I tried version 0.6.4 and a few times and does not work. But mainly I wiped zkoro Pokémon from your inventory. be careful not to try

**Comment by jiminchanga** [comment] 2016-08-04 14:39
yeah he's trolling

**Comment by ViezeOudeMan** [comment] 2016-08-04 14:49
troller ..

**Comment by eeelmaito** [comment] 2016-08-04 14:59
I'll test it for this day and then share it if everything works fine for 12 hours.

**Comment by akselrudi** [comment] 2016-08-04 15:04
Come on let us test too :3

**Comment by reacherwick** [comment] 2016-08-04 15:08
He is fake

**Comment by kokojambo1** [comment] 2016-08-04 15:13
eeelmaito!! If it really works for you I am ready to send my explanation of how to update or fix it if it works I pay you $ 50 in my e-mail address nirko1800@gmail.com

**Comment by gtpokefan** [comment] 2016-08-04 15:14
I thought he was lying but I gave a shot at messing around with the code and it started working without spamming the no pokestops found error. Im test it out for an hour and see if no problems pop up and then ill post it on the thread guys!

**Comment by jiminchanga** [comment] 2016-08-04 15:14
don't send him money wtf ^

**Comment by jiminchanga** [comment] 2016-08-04 15:15
thanks @gtpokefan

**Comment by kokojambo1** [comment] 2016-08-04 15:15
Who sends me an explanation in the next 10 minutes I transfer the account to his $ 50 paypel

**Comment by jiminchanga** [comment] 2016-08-04 15:16
you're gonna get scammed lol

**Comment by kokojambo1** [comment] 2016-08-04 15:16
Who sends me an explanation in the next 10 minutes I transfer the account to his $ 50 paypel

**Comment by eeelmaito** [comment] 2016-08-04 15:18
kokojambo1 I'll email you shortly. No need for payment tho lol

**Comment by akselrudi** [comment] 2016-08-04 15:19
If anyone would help me i would be very grateful :)

 My e mail: rudi.aksel@gmail.com

**Comment by kokojambo1** [comment] 2016-08-04 15:20
I'm dead serious so I have it. Who will help me receive $ 50

**Comment by kokojambo1** [comment] 2016-08-04 15:21
My e mail: nirko1800@gmail.com

**Comment by mikegrimmers** [comment] 2016-08-04 15:25
Please just post the fix on here! It would be greatly appreciated

**Comment by kuntoharr** [comment] 2016-08-04 15:26
Everyone calm down lol

**Comment by reacherwick** [comment] 2016-08-04 15:27
Careful fourth party program

**Comment by akselrudi** [comment] 2016-08-04 15:27
So no one have got it working yet? :)

**Comment by kokojambo1** [comment] 2016-08-04 15:29
eeelmaito ?? I'm waiting for you bro !! (:

**Comment by gtpokefan** [comment] 2016-08-04 15:30
The fix is working perfectly so far, gonna post it on the thread asap! Thanks for waiting you guys

**Comment by reacherwick** [comment] 2016-08-04 15:32
Nice :)

**Comment by kokojambo1** [comment] 2016-08-04 15:42
???

**Comment by reacherwick** [comment] 2016-08-04 15:47
Share the link please :)

**Comment by adannarjona** [comment] 2016-08-04 15:49
any news? my e-mail: adan.arjona@gmail.com

**Comment by kokojambo1** [comment] 2016-08-04 15:51
Friends I can not wait !! Who first champion to help me?

**Comment by vyshu007** [comment] 2016-08-04 15:52
@gtpokefan  waiting for your reply broooo

**Comment by gtpokefan** [comment] 2016-08-04 15:53
Sorry for the delay guys, I got softbanned using it so im trying to find a fix for that as well. I'll keep you guys posted.

**Comment by mikegrimmers** [comment] 2016-08-04 15:53
Btw guys, little heads up - if you set your co-ordinates to Times Square, New York with a radius of 5000. Prepare to be amazed.

**Comment by Kenshayy** [comment] 2016-08-04 15:55
How can I fix that?

**Comment by beanzooo** [comment] 2016-08-04 15:58
can someone please help me with what i need to do to make it work again

**Comment by gigi756** [comment] 2016-08-04 16:00
They are trolling

**Comment by JSleemanII** [comment] 2016-08-04 16:01
pretty sure eeelmaito and gtpokefan are the same troll. It looks like all bots are down that are derived from the reverse engineered API. 
http://www.i4u.com/2016/08/114046/niantic-breaks-pokemon-go-apis-and-all-bots-and-trackers-based-apis

**Comment by beanzooo** [comment] 2016-08-04 16:01
https://github.com/NECROBOTIO/NecroBot/commit/9b3faa739ca2dfe1e0b86a99c9bec65509d1e9e5

**Comment by TalkativeTom** [comment] 2016-08-04 16:01
heyo

**Comment by iXono** [comment] 2016-08-04 16:01
I think necrobot's servers are out

**Comment by TalkativeTom** [comment] 2016-08-04 16:02
oh!

**Comment by TalkativeTom** [comment] 2016-08-04 16:02
no necrobot isnt working with the new version of poke go

**Comment by iXono** [comment] 2016-08-04 16:03
i tested it yesterday and it was working

**Comment by Kenshayy** [comment] 2016-08-04 16:05
Now say me (ATTENTION) You're outside of your defined radius! Walking to start (2474.04292241981m away) in 5 seconds. Is your LastPos.ini file correct?
How can I fix this?

**Comment by TalkativeTom** [comment] 2016-08-04 16:05
i have the problem : there are no usable pokestops in yiur area

**Comment by TalkativeTom** [comment] 2016-08-04 16:05
:(

**Comment by Kenshayy** [comment] 2016-08-04 16:06
Me too now.

**Comment by TheXepi** [comment] 2016-08-04 16:06
Yesterday it was working, but around 8pm / 9pm it changed

**Comment by gtpokefan** [comment] 2016-08-04 16:07
Yes, the new version of necrobot along with most other bots have stopped working because niantic has found the coding they were using for their programs allowing them to work. Im trying to develop a different code that niantic has not already stopped from working to allow everyone to stop getting the error "No usable pokestops in your area" from spamming. The fix im working on is only for necrobot from what I know so far and only for the pokestop error as well. It may work for other errors/bots but I have to get it working 100% first before I know for sure. Thanks for the patience guys.

**Comment by BlackRavine** [comment] 2016-08-04 16:09
@gtpokefan Can't wait until it fixed.. thanks for the effort, man :+1:

**Comment by kokojambo1** [comment] 2016-08-04 16:10
ב אוג׳ 4, 2016 19:05, TalkativeTom כתב:

:(Please help said that they have a solution
—Please help said that they have a solutionYou are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Kenshayy** [comment] 2016-08-04 16:10
In how many hours can you fix  that?

**Comment by beanzooo** [comment] 2016-08-04 16:11
if anyone knows of anything that's working please give me a message or share for everyone, thanks

**Comment by kokojambo1** [comment] 2016-08-04 16:11
Please help said that they have a solution

**Comment by iXono** [comment] 2016-08-04 16:12
Guys, we must be patient and wait

**Comment by TheXepi** [comment] 2016-08-04 16:13
@gtpokefan is working on it, solve to this problem will be probably tomorrow with a new update to the necrobot. Or even today.... Stay patient ヽ(⌐■◡■)ﾉ

**Comment by JSleemanII** [comment] 2016-08-04 16:14
@kokojambo1 Please ignore @gtpokefan and @eeelmaito. They are trolling you getting your hopes up. This is a big problem that will not be fixed quickly. You are better off keeping track of the updates here
https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/

**Comment by akselrudi** [comment] 2016-08-04 16:15
Thanks for the info guys :)!

**Comment by kokojambo1** [comment] 2016-08-04 16:22
In short, you have a link or a way to fix this make me very happy. I'm waiting for an update here

**Comment by maximumeffort91** [comment] 2016-08-04 16:24
I know the bot won't catch Pokemon but will it still hatch eggs? Or is the movement dependent on stops?

**Comment by pandorasky21** [comment] 2016-08-04 16:51
Guys, its working now! thanks to gtpokefan for sharing to me the updated bot. You want it? download here:

www.WTFpleaseBEpatientMOTHAFACKAdevAREworkingONitBITCH.com

you are welcome :)

**Comment by Venin87** [comment] 2016-08-04 16:52
?

**Comment by GreenGoblinz** [comment] 2016-08-04 16:52
I don't see the point of this thread.

**Comment by kokojambo1** [comment] 2016-08-04 16:59
@pandorasky21 the link is not working !!!!

**Comment by jiminchanga** [comment] 2016-08-04 17:01
obviously not, did you read the link title or not?^

**Comment by pandorasky21** [comment] 2016-08-04 17:01
Ahahaha of course :D
guys please be patient and please dont get scammed ;)

**Comment by vyshu007** [comment] 2016-08-04 17:03
@pandorasky21  nailed it bro .!

**Comment by vyshu007** [comment] 2016-08-04 17:04
all of us are waiting. Let's wait patiently for the best to happen :) :+1:

**Comment by Golden725** [comment] 2016-08-04 17:05
not working here

**Comment by GreenGoblinz** [comment] 2016-08-04 17:09
@jiminchanga I wrote that because this issue is already being addressed by multiple bot developers.

**Comment by jiminchanga** [comment] 2016-08-04 17:10
I meant that comment for @kokojambo1, not you

**Comment by modeminho** [comment] 2016-08-04 17:11
these bots are done. y'all need to move on with your lives.

**Comment by jiminchanga** [comment] 2016-08-04 17:12
gotta have hope :)

**Comment by syarifmaula** [comment] 2016-08-04 17:17
bots still down?

**Comment by GreenGoblinz** [comment] 2016-08-04 17:27
They'll come back when @jiminchanga gives me those digits.

**Comment by jiminchanga** [comment] 2016-08-04 17:31
😂😂😂

**Comment by gtpokefan** [comment] 2016-08-04 17:38
Guys, this is a fix that might take a few hours if not a day or two, just be patient and don't believe anyone that will give you a "fix" if you pay them money. Just wait for real fixes to be developed trust me you guys aren't the only ones that want the bots to be working again. Thanks to all of you guys :)

**Comment by kokojambo1** [comment] 2016-08-04 17:48
If it really works for you I am ready to send my explanation of how to update or fix it if it works I pay you $ 50 in my e-mail address nirko1800@gmail.com

**Comment by helomar28** [comment] 2016-08-04 17:50
already returned to work ??

**Comment by hasbiputro** [comment] 2016-08-04 18:12
@gtpokefan we all waiting for up again, good job !!

**Comment by GreenGoblinz** [comment] 2016-08-04 18:27
Why you laughing.

**Closed** 2016-08-04 18:36 UTC

**Comment by eeelmaito** [comment] 2016-08-04 18:53
Bot is 100% working after replacing these few lines in the code. I'll upload the new script here within 2 hours.

**Comment by jiminchanga** [comment] 2016-08-04 18:55
@greengoblinz cause u funny

**Comment by iXono** [comment] 2016-08-04 18:56
@eeelmaito We'll wait

**Comment by kokojambo1** [comment] 2016-08-04 19:06
If you are truthful and you're going to get us the bot you king !!! But if not will know you really not nice @eeelmaito

**Comment by GrandSavior** [comment] 2016-08-04 19:13
trouble troble troble.. --"

**Comment by GreenGoblinz** [comment] 2016-08-04 19:25
@jiminchanga  So we cant make babies?

**Comment by jiminchanga** [comment] 2016-08-04 19:26
no thanks I'm gay

**Comment by GrandSavior** [comment] 2016-08-04 19:29
if bot pokemon down.. t_t i'll find free bot 7k, anyone can help me??

**Comment by GreenGoblinz** [comment] 2016-08-04 19:32
@jiminchanga So you're a Lickitongue huh

**Comment by jiminchanga** [comment] 2016-08-04 19:35
@greengoblinz lol

**Comment by rey306** [comment] 2016-08-04 19:39
nothing working yet?

**Comment by rey306** [comment] 2016-08-04 19:39
i only got to lvl 25 with the bot lol

**Comment by TheXepi** [comment] 2016-08-04 19:39
Yep. nothing

**Comment by rey306** [comment] 2016-08-04 19:40
rip i guess ill have to go outside now lol

**Comment by iXono** [comment] 2016-08-04 19:59
I would like to go outside, but it's 10pm ;o

**Comment by kokojambo1** [comment] 2016-08-04 20:09
There is new for the repair?

**Comment by ViezeOudeMan** [comment] 2016-08-04 20:42
fix out yet ?????

**Comment by GreenGoblinz** [comment] 2016-08-04 20:54
We have created a Twitter Profile to keep you guys always Up 2 Date! Follow us for news regarding our Bot or Pokemon Go and dont forget to spread the Word :D
https://twitter.com/PokeMobBot

**Comment by TumsArentCandy** [comment] 2016-08-04 22:15
This is bullshit, if anyone has a fix please comment it here asap.

**Comment by HefferWolfe** [comment] 2016-08-04 22:17
PokeMobBot ‏@PokeMobBot  30 мин.30 минут назад
We know most of the payload that goes into the "unknown6" hash, still working on the encryption/signature algorithm itself. (21:13 @ Reddit)

**Comment by GreenGoblinz** [comment] 2016-08-05 00:20
They have a working API guys they're just testing it now.

**Comment by Asriandy** [comment] 2016-08-05 00:28
Yeyyyy i read some forum someone has fix it ^^

**Comment by rey306** [comment] 2016-08-05 00:28
Can anyone drop a link for it?

**Comment by bobbywatsup212** [comment] 2016-08-05 00:45
So will it just be a frwsh update that will fix it or do we need to do something on our end too

**Comment by penggilingan** [comment] 2016-08-05 02:03
well hopefully we can get fixed version soon ^^

**Comment by WillDKe** [comment] 2016-08-05 04:33
# **# Soo guyz any news? :/ same problem here, no pokestops or catch pokemon.**

**Comment by akselrudi** [comment] 2016-08-05 09:27
Guys the fastest way to get notified when they get out a fix would be to follow them on twitter

https://twitter.com/PokeMobBot

**Comment by vyshu007** [comment] 2016-08-05 10:20
any update??

**Comment by asskickrelol** [comment] 2016-08-05 11:54
Still "no usable pokestops"

**Comment by vyshu007** [comment] 2016-08-05 15:14
guyzz?

**Comment by akselrudi** [comment] 2016-08-05 15:20
Yeah?

**Comment by MichalKync** [comment] 2016-08-05 15:30
still not work,uaaa,earth over!!!!

**Comment by a7mag3ddon** [comment] 2016-08-05 17:28
Read this for updates instead of your incessant asking for " is it working "

https://www.reddit.com/r/pokemongodev/comments/4w1cvr/pokemongo_current_api_status/?st=irgloyz7&sh=e889c2ae

**Comment by InsaanFr** [comment] 2016-08-06 11:35
I have same problem,
First I think my old account that using bot  got softban or banned, So I try a new account and It still no usable pokestop for my new account

I think this is not softban

**Comment by DheekeyCarey** [comment] 2016-08-06 17:20
I think I have figured something out too... working on it

**Comment by r3kylen** [comment] 2016-08-06 20:02
Someone know Anything ?:) I still just got this message : https://gyazo.com/82975f29c6453adfb6394864ced2b925

**Comment by Jazed** [comment] 2016-08-06 20:37
Niantic broke the API, we're working on solving this as we speak.
