### ISSUE TITLE
BIG problem, cant run PokeMobBot at all!

### ISSUE THREAD

**Issue by Gardagger** [PocketMobsters/PokeMobBot#556] opened 2016-08-03 20:07 UTC
everytime it starts up it does this https://gyazo.com/c9ce60e1a41280c589aec3690872cbae

**Comment by MarioVX** [comment] 2016-08-03 20:08
I second this, same for me.

**Comment by giacomofabbri** [comment] 2016-08-03 20:08
Same as yours!! I hope that they will solve this!!

**Comment by globus243** [comment] 2016-08-03 20:09
confirmed.

**Comment by nuggetbucket** [comment] 2016-08-03 20:11
same over here :(

**Comment by ccman32** [comment] 2016-08-03 20:11
Same problem here.

**Comment by JeffBrown04** [comment] 2016-08-03 20:11
+1 We may have been perma banned, but lets not get too excited yet.

**Comment by Gardagger** [comment] 2016-08-03 20:11
Perma banned from what?

**Comment by quelladesoreta** [comment] 2016-08-03 20:11
Same here! I want to keep cheating!

**Comment by nuggetbucket** [comment] 2016-08-03 20:12
not perma
can access on mobile

**Comment by MarkoIvanetic** [comment] 2016-08-03 20:12
no one is perma banned lol

**Comment by vdellevoet** [comment] 2016-08-03 20:12
same here...

**Comment by Gardagger** [comment] 2016-08-03 20:12
Yeah ikr, i can access GO on my phone, just the cheat isnt working

**Comment by doodlemeat** [comment] 2016-08-03 20:13
The pattern those pixels appear is the same on my computer screen. I confirm this.

**Comment by MarkoIvanetic** [comment] 2016-08-03 20:13
at the moment ptc is Unstable
https://go.jooas.com/

**Comment by ccman32** [comment] 2016-08-03 20:13
I will take a look at the source code and check what's actually going on.

**Comment by Gardagger** [comment] 2016-08-03 20:14
Hahah YEAH! LETS GET ON DIS!

**Comment by ruturajvy** [comment] 2016-08-03 20:14
Same here! This issue started just 5 mins ago.. it was working fine before.

**Comment by megaDrummerxxl** [comment] 2016-08-03 20:14
same here, using google login

**Comment by Gardagger** [comment] 2016-08-03 20:14
Its probably Cuz the server went unstable

**Comment by globus243** [comment] 2016-08-03 20:14
def no ban, login and pokestops working

**Comment by Phused** [comment] 2016-08-03 20:14
Looks like mine isn't even letting me log in...

**Comment by Gardagger** [comment] 2016-08-03 20:15
Glad a lot of people are having this issue, i thought i done goofed

**Comment by steffo78** [comment] 2016-08-03 20:16
Maybe something to do with the latest update? Old versions of the Pokemon GO app aren't working either since the new update.

**Comment by Gardagger** [comment] 2016-08-03 20:17
No i think it has to do with what MarkoIvanetic said

**Comment by richieza** [comment] 2016-08-03 20:18
back up

**Comment by steamlab13** [comment] 2016-08-03 20:18
same lol!
![trouble](https://cloud.githubusercontent.com/assets/20803983/17380594/8fa31ba4-59d0-11e6-8dd6-df26c7cafd9d.png)

**Comment by steffo78** [comment] 2016-08-03 20:18
I have a google log in, so I'm not using PTC

**Comment by sddds** [comment] 2016-08-03 20:18
thx @ccman32

**Comment by Gardagger** [comment] 2016-08-03 20:18
BACK UP!

**Comment by ccman32** [comment] 2016-08-03 20:19
@sddds I haven't done anything so far except opening the project xD

**Comment by ZapPhoenix** [comment] 2016-08-03 20:19
no pokemon found in my area?

**Comment by roelstorms** [comment] 2016-08-03 20:19
Anyone with PTC login having the issue?

**Comment by Gardagger** [comment] 2016-08-03 20:19
Yeah

**Comment by MarkoIvanetic** [comment] 2016-08-03 20:19
Server offline
https://go.jooas.com/

**Comment by quelladesoreta** [comment] 2016-08-03 20:19
It's back up but seems a lot slower now

**Comment by Gardagger** [comment] 2016-08-03 20:19
Spamming Egg Incubators no Pokestops and Radius to small

**Comment by roelstorms** [comment] 2016-08-03 20:20
Back up, confirmed

**Comment by quelladesoreta** [comment] 2016-08-03 20:20
"No usable PokeStops found in your area"

**Comment by Gardagger** [comment] 2016-08-03 20:20
Yep

**Comment by azkataphrakt** [comment] 2016-08-03 20:20
"No usable PokeStops found in your area"
lat and lon changed - find the ones you used before or get a new one

**Comment by ccman32** [comment] 2016-08-03 20:20
@quelladesoreta Same but I guess this problem will be fixed by itself after a while

**Comment by steamlab13** [comment] 2016-08-03 20:21
@MarkoIvanetic Poodlecorp?? xD

**Comment by Gardagger** [comment] 2016-08-03 20:21
THE SERVERS ARE OFFLINE

**Comment by qroneL** [comment] 2016-08-03 20:21
back up confirmed, but bots got kinda soft ban. no poke or pokestop around

**Comment by Gardagger** [comment] 2016-08-03 20:21
ITS THE END OF THE WORLD

**Comment by Gardagger** [comment] 2016-08-03 20:21
POKEMON GO IS DOWN

**Comment by vdellevoet** [comment] 2016-08-03 20:21
Same here, no pokestops found in the area...

**Comment by steamlab13** [comment] 2016-08-03 20:22
POODLECORP CONFIRMED!!! 0_0

**Comment by ruturajvy** [comment] 2016-08-03 20:22
It's not a server issue.. The game is working nicely on the app. Just the bot is not working.

**Comment by roelstorms** [comment] 2016-08-03 20:22
Maybe an update that broke functionality?

**Comment by Gardagger** [comment] 2016-08-03 20:23
Maybe

**Comment by Gardagger** [comment] 2016-08-03 20:23
But why would it happen just now

**Comment by steamlab13** [comment] 2016-08-03 20:23
![that sucks :((](https://cloud.githubusercontent.com/assets/20803983/17380740/4385219e-59d1-11e6-98e2-3658da3dfe27.png)

**Comment by ccman32** [comment] 2016-08-03 20:23
@Gardagger why would it happen at any other point of time?

**Comment by globus243** [comment] 2016-08-03 20:23
confirmed that bot is running again, but no pokestops or pokemons are found.
App seems to run ok, stops and spawns working. so it's "just" the bot.

good thing I hit lvl 30 yesterday

**Comment by Gardagger** [comment] 2016-08-03 20:24
Why would it just shutoff now and not when the update came out

**Comment by ccman32** [comment] 2016-08-03 20:24
@globus243 how long until lvl 30? I started yesterday and got to lv 15 now XD

**Comment by Gardagger** [comment] 2016-08-03 20:24
or was there an update today?

**Comment by globus243** [comment] 2016-08-03 20:24
niantics wouldnt switch of there servers on day 1 of update

**Comment by roelstorms** [comment] 2016-08-03 20:24
Well, I don't believe they could modify the API since the APP should be updated accordingly.

**Comment by ruturajvy** [comment] 2016-08-03 20:24
No.. not the update.. the update worked fine for a day or 2

**Comment by qroneL** [comment] 2016-08-03 20:24
so it means lets login with nox and get some gyms everybody.

**Comment by Gardagger** [comment] 2016-08-03 20:25
@ccman32 It took my bot 2-3 days of straight being on no problems to hit 30

**Comment by richieza** [comment] 2016-08-03 20:25
Forced to update to new version of app now... (could play on old version - probably a security enforcement)

**Comment by ccman32** [comment] 2016-08-03 20:25
@Gardagger alright thx for the info

**Comment by Gardagger** [comment] 2016-08-03 20:25
Yeah no one start the bot after you download the new update, might be a perma ban sweep

**Comment by globus243** [comment] 2016-08-03 20:25
@ccman32 started friday at lvl 16 and hit it yesterday

**Comment by ccman32** [comment] 2016-08-03 20:26
I already downloaded the new version about 1-2 hours ago while the bot was still running and got no problems or bans at all.

**Comment by bbekkis** [comment] 2016-08-03 20:27
read this one, and my answer from there.
> https://github.com/PocketMobsters/PokeMobBot/issues/558

**Comment by ccman32** [comment] 2016-08-03 20:27
But I will just keep this bot running for a while and if nothing changes try it again tomorrow, there is not much to do about it anyway unless you know enough about the source code/project to try fixing it by yourself.

**Comment by DorianGui** [comment] 2016-08-03 20:29
its time to set up fake gps app on cell phone and go get some gyms lol

**Comment by Gardagger** [comment] 2016-08-03 20:29
@DorianGui  thats kinda lame, you're cheating, no reason to ruin the game for everybody else

**Comment by PhantomBug** [comment] 2016-08-03 20:30
I thought to mention this, as I always run the oldest client possible, that the client support for version 29.3 has ended today at the crash/opening of Pokemon GO on my mobile an hour ago or something.
So the servers have been upgraded, yeah...
I dont know if they start perma banning dough

**Comment by DorianGui** [comment] 2016-08-03 20:31
@Gardagger so botting is not called cheating?

**Comment by Gardagger** [comment] 2016-08-03 20:32
It is cheating but just using to catch pokemon and to level up doesnt affect anyone, taking over gyms do hurt the people that arent cheating

**Comment by sddds** [comment] 2016-08-03 20:33
@DorianGui unbanner isn't working either because of the pokestop issue. How are you gymming?

**Comment by Gardagger** [comment] 2016-08-03 20:33
true

**Comment by bbekkis** [comment] 2016-08-03 20:34
@sddds easy, just spin the stop ~40-45 times and go back to the gym.

**Comment by DorianGui** [comment] 2016-08-03 20:34
i got softbanned the moment the bot went down, i just checked i get unbanned serval minutes ago

**Comment by sddds** [comment] 2016-08-03 20:36
ok

**Comment by CptnKvin** [comment] 2016-08-03 20:38
Other bots neither work ^^'

**Comment by Gardagger** [comment] 2016-08-03 20:38
@DorianGui same

**Comment by sddds** [comment] 2016-08-03 20:40
Quote from ownedcore "They changed the API time to 10 seconds... so RIP to every bot & snipe bot"

**Comment by steffo78** [comment] 2016-08-03 20:42
@Gardagger Actually it is. It's not because the bot is not attacking gyms, that you won't afterwards. The higher your level is, the better the pokemons are you can catch. So when you attack gyms with high level pokemons that a bot has catched for you, its literately cheating. Because people who don't use bots or gps spoofing have to do all the work by themselfs ;) Not that I care, bc I use the bot myself, but I think it's more honest to say it is cheating.

**Comment by Gardagger** [comment] 2016-08-03 20:46
@Steffo78 i said its cheating, im agreeing with you

**Comment by ccman32** [comment] 2016-08-03 20:47
@sddds And "API time" is something that everyone is expected to know or what?

**Comment by steffo78** [comment] 2016-08-03 20:48
@Gardagger Yep I saw that the moment I posted my comment. Didn't read that carefully :)

**Comment by sddds** [comment] 2016-08-03 20:49
@sddds It's basically the interaction delay between bot and server. The bot makes a call to the server that sayys we caught x pokemon with perfect throw, now calculate whether it's caught or not.

**Comment by Kassius509** [comment] 2016-08-03 21:00
https://www.reddit.com/r/pokemongodev/comments/4vuijn/psa_minimum_scan_refresh_now_10s/

**Comment by steffo78** [comment] 2016-08-03 21:01
Definitely an API update. The app was recently forced to update to the new version. My guess is they had two API's running, the old one and a new one. After the forced update they probably stopped using the old one. And that's what gives the error. Just a guess of course.

**Comment by MarkoIvanetic** [comment] 2016-08-03 21:03
devs are working on it already 
https://github.com/PocketMobsters/PokeMobBot/commit/52e7c7b6ba398eb9c96fd007be168513f9bed44a

**Comment by Gardagger** [comment] 2016-08-03 21:15
Yay progress!

**Comment by vdellevoet** [comment] 2016-08-03 21:16
Anyone who can give an indication of how long it will take before the update comes out?

**Comment by Gardagger** [comment] 2016-08-03 21:17
no clue

**Comment by vdellevoet** [comment] 2016-08-03 21:18
I live in amsterdam so its pretty late already around here and i want to make sure the bot is running tonight

**Comment by Gardagger** [comment] 2016-08-03 21:19
how long until its Tonight for you?

**Comment by charliemate** [comment] 2016-08-03 21:19
probably not tonight but one can hope!

**Comment by Gardagger** [comment] 2016-08-03 21:19
Yeah i was gonna say it might take a day OR two if its REAL complicated

**Comment by vdellevoet** [comment] 2016-08-03 21:22
In a 1 a 2 hours, i know it to much to ask haha

**Comment by qroneL** [comment] 2016-08-03 21:23
Compiled latest code but still no luck, lets wait a little more.

**Comment by PhantomBug** [comment] 2016-08-03 21:26
I am banned as it was in an other continent that I was .. going Right now to a pokestop as gyms are not werking (error)

**Comment by charliemate** [comment] 2016-08-03 21:27
i can go to pokestops but when i try to catch pokemon I get error :( but i can catch mons on my other account

**Comment by PhantomBug** [comment] 2016-08-03 21:42
I cant do shit :s

Op 3 aug. 2016 11:27 p.m. schreef "charliemate" <notifications@github.com>:

**Comment by Prayme** [comment] 2016-08-03 22:29
any news?

**Comment by charliemate** [comment] 2016-08-03 22:38
yes update: still not working.

**Comment by Gardagger** [comment] 2016-08-03 22:44
haha

**Comment by fitjrian** [comment] 2016-08-03 23:58
waiting...

**Comment by thtguy365** [comment] 2016-08-04 00:10
Getting a new issue after update something about  system.net.http.httprequestexeption

**Comment by zippy1979** [comment] 2016-08-04 15:57
Thank you guys for working on this, it is appreciated!

**Comment by Valmere** [comment] 2016-08-04 17:18
Bot's currently not working, check the announcement channel in our discord.

**Closed by Valmere** 2016-08-04 17:18 UTC
