### ISSUE TITLE
Outside of your defined radius. Maybe teleport if starting point is to far away ?

### ISSUE THREAD

**Issue by psentenac** [PocketMobsters/PokeMobBot#85] opened 2016-07-31 13:53 UTC
[15:38:04] Looking for incense Pokemon...
[15:38:06] Name: Ici Vécu Jules Romains  XP: 50, Gems: 0, Items: 1 x ItemRazzBerry, 2 x ItemPokeBall
[15:38:07] [Sniper] Sniping a Porygon with 63 IV at 35.694093428867,139.72524786694...
[15:38:10] (CatchEscape) | (Normal) Porygon Lvl: 13 CP: (585/628) IV: 61.00% | Chance: 33.22% | 9722114.89m dist | with a GreatBall (1 left). | 
[15:38:13] (CatchSuccess Attempt #2) | (Normal) Porygon Lvl: 13 CP: (585/628) IV: 61.00% | Chance: 33.22% | 9722114.89m dist | with a GreatBall (0 left). | Candies: 344
[15:38:20] [Sniper] Sniping a Aerodactyl with unknown IV at 51.5339,0.7135...
[15:38:26] [Sniper] Sniping a Snorlax with unknown IV at 38.882225875208,-77.225830797252...
[15:38:33] Niantic Servers unstable, throttling API Calls.
[15:38:34] [Current Inventory] Pokeballs: 21 | Greatballs: 0 | Ultraballs: 1 | Masterballs: 0
[15:38:34] Checking for balls to recycle, keeping 120
[15:38:34] Checking for potions to recycle, keeping 50
[15:38:34] Checking for revives to recycle, keeping 20
[15:38:34] 1x ItemPotion
[15:38:39] Incubator status update: 2.11km left
[15:38:39] Incubator status update: 2.99km left
[15:38:39] Incubator status update: 2.99km left
[15:38:39] Incubator status update: 2.99km left
[15:38:39] Incubator status update: 3.33km left
[15:38:39] Incubator status update: 3.33km left
**[15:38:39] You're outside of your defined radius! Walking to start (6182966.62862164m away) in 5 seconds. Is your Coords.ini file correct?**

**Comment by FatSacks** [comment] 2016-07-31 14:09
So you teleport there and get instantly soft-banned?
Seems like a legit idea...

**Comment by psentenac** [comment] 2016-07-31 14:20
Please, feel free to propose an other quick fix while looking for the real reason of this unwanted teleport. Mine is not perfect, i agree but it's better than having the bot stop working.

**Comment by LuckyCharm7** [comment] 2016-07-31 14:33
well it's working fine for me (the unban), i tried to go from central park new york to tokyo disneyland, in less then a minute or so i was banned, maybe a minute later (i let the bot working even when it was showing the same issue) the bot did is job and now i'm able to farm again :D 
![tokyo disneyland stats](https://cloud.githubusercontent.com/assets/20751445/17277126/990a00fa-5709-11e6-8baf-a19940ccd582.png)

**Comment by UntilSunrise** [comment] 2016-07-31 21:12
duplicate of #147

**Closed by UntilSunrise** 2016-07-31 21:12 UTC
Labels: needs verification
