### ISSUE TITLE
Outside of defined radius

### ISSUE THREAD

**Issue by ShakyDetox** [PocketMobsters/PokeMobBot#144] opened 2016-07-31 20:28 UTC
"MaxTravelDistanceInMeters": 10000,

But I always get the outside of defined radius after a while, then it says walking back but it takes ages seems like its not walking back.

**Comment by klemax** [comment] 2016-07-31 20:33
+1

**Comment by UntilSunrise** [comment] 2016-07-31 20:50
duplicate of #147

**Closed by UntilSunrise** 2016-07-31 20:50 UTC
