### ISSUE TITLE
Full inventory on v1.0.1

### ISSUE THREAD

**Issue by vfuyong** [PocketMobsters/PokeMobBot#216] opened 2016-08-01 10:56 UTC
Inventory can be full but recycle does not kick in for potion, revive and berry. Pokeshop does not give any loot. After some time, all balls will be exhausted. 

This is a critical bug.

**Comment by Fenixxia** [comment] 2016-08-01 11:01
The program does not use the berries to catching pokémon, even if the terms of use set at minimum.

**Comment by MarioVX** [comment] 2016-08-01 11:10
Can confirm this is a serious issue that came up with 1.0.1. I've tried numerous different parameter settings to avoid this but I just can't get the bot to recycle anything since the update. Hope this gets fixed soon.

**Comment by vapp13** [comment] 2016-08-01 11:19
With this settings, the bot keeps my inventory working properly, it prioritize the ultraball, currently around 170 ultraballs, 26 great balls and 3 pokeballs. Every 5 pokestops it recycle the worse balls to keep my pokeballs in 200 totals. Same with the potions.

  "TotalAmountOfPokeballsToKeep": 200,
  "TotalAmountOfPotionsToKeep": 60,
  "TotalAmountOfRevivesToKeep": 10,

At the moment there isn't a way to recyle the berrys, but this one keep my berrys low cause I don't usually need them:
  "UseBerryBelowCatchProbability": 0.4,

**Comment by robertosartori** [comment] 2016-08-01 11:52
I can confirm: potion are not recycle in 1.0.1

**Comment by Imodorox** [comment] 2016-08-01 12:01
I can confirm: potion are not recycle in 1.0.1

**Comment by vfuyong** [comment] 2016-08-01 12:04
This happens when inventory is high. I noticed when inventory is low, recycle DOES happen. I think the math calculation is not correct.

**Comment by raftheunis87** [comment] 2016-08-01 12:30
+1

**Comment by Zenithxm** [comment] 2016-08-01 12:52
*watching

**Comment by mennas** [comment] 2016-08-01 12:55
I dont know you set your setting, mine work properly

**Comment by mennas** [comment] 2016-08-01 12:56
"RecycleInventoryAtUsagePercentage": 0.0,

**Comment by DurtyFree** [comment] 2016-08-01 16:07
This should be addressed in the newest release, coming this evening.

**Closed by DurtyFree** 2016-08-01 16:07 UTC
