### ISSUE TITLE
Too frequent bulk evolution

### ISSUE THREAD

**Issue by rrelict** [PocketMobsters/PokeMobBot#129] opened 2016-07-31 18:07 UTC
There is too frequent bulk evolution:
![evolution_timeout_](https://cloud.githubusercontent.com/assets/8160881/17278266/c8358770-5761-11e6-89ba-8c74b128eccf.png)
Config:
"DelayBetweenPlayerActions": 5000,
"UseLuckyEggsMinPokemonAmount": 100,
"UseLuckyEggsWhileEvolving": true

May be we need the _DelayPocemonEvolution_ parameter?

**Comment by DurtyFree** [comment] 2016-07-31 19:52
Duplicate of #138

**Closed** 2016-07-31 19:53 UTC
Labels: duplicate
